# Generated by Django 3.2.8 on 2021-10-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='our_team/')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_designation', models.CharField(max_length=50)),
                ('client_testimonial', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='testimonial/')),
            ],
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='twitter',
            new_name='linkedin',
        ),
        migrations.AddField(
            model_name='setting',
            name='address',
            field=models.TextField(default='www.linkedin.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='youtube',
            field=models.URLField(blank=True),
        ),
    ]
