# Generated by Django 3.2.8 on 2021-10-25 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('Installment', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('land_image', models.ImageField(blank=True, upload_to='land/')),
            ],
            options={
                'verbose_name': 'Land',
                'verbose_name_plural': 'Lands',
            },
        ),
        migrations.CreateModel(
            name='LandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('land_image', models.ImageField(blank=True, upload_to='land/')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_image', to='property.land')),
            ],
            options={
                'verbose_name': 'LandImage',
                'verbose_name_plural': 'LandImages',
            },
        ),
    ]
