# Generated by Django 3.2.8 on 2021-10-31 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20211030_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='land_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='land_category', to='property.landtype'),
        ),
    ]
