# Generated by Django 3.2.8 on 2021-10-31 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_land_land_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='landtype',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
