# Generated by Django 3.2.8 on 2021-10-31 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20211031_0540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='land',
            old_name='Installment',
            new_name='installment',
        ),
    ]
