# Generated by Django 3.2.8 on 2021-11-02 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_rename_installment_land_installment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('katha', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('side', models.CharField(choices=[('Front Side', 'Front Side'), ('South', 'South'), ('East', 'East'), ('North', 'North'), ('West', 'West')], max_length=50)),
                ('plot', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('job_title', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_query', to='property.land')),
            ],
        ),
    ]
