# Generated by Django 3.2.8 on 2021-11-02 01:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_landquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='landquery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landquery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
